services:
    sortomatic:
        build:
            context: ../
            dockerfile: Sortomatic/Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - ./data:/data
            - .:/app
            - ../NiceTheme:/deps/NiceTheme
        working_dir: /app